// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchResponse struct {
	Error                string     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Results              []*Content `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SearchResponse) GetResults() []*Content {
	if m != nil {
		return m.Results
	}
	return nil
}

type Content struct {
	Id                   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EntryType            int32          `protobuf:"varint,2,opt,name=entryType,proto3" json:"entryType,omitempty"`
	HttpsBlock           int32          `protobuf:"varint,3,opt,name=httpsBlock,proto3" json:"httpsBlock,omitempty"`
	RegistryUpdateTime   int64          `protobuf:"varint,4,opt,name=registryUpdateTime,proto3" json:"registryUpdateTime,omitempty"`
	Decision             *Decision      `protobuf:"bytes,5,opt,name=decision,proto3" json:"decision,omitempty"`
	IncludeTime          int64          `protobuf:"varint,6,opt,name=includeTime,proto3" json:"includeTime,omitempty"`
	BlockType            string         `protobuf:"bytes,7,opt,name=blockType,proto3" json:"blockType,omitempty"`
	Hash                 string         `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"`
	Ts                   int64          `protobuf:"varint,9,opt,name=ts,proto3" json:"ts,omitempty"`
	U2Hash               uint32         `protobuf:"varint,10,opt,name=u2Hash,proto3" json:"u2Hash,omitempty"`
	Urls                 []*URL         `protobuf:"bytes,11,rep,name=urls,proto3" json:"urls,omitempty"`
	Ip4S                 []*IPv4Address `protobuf:"bytes,12,rep,name=ip4s,proto3" json:"ip4s,omitempty"`
	Ip6S                 []*IPv6Address `protobuf:"bytes,13,rep,name=ip6s,proto3" json:"ip6s,omitempty"`
	Subnets              []*Subnet      `protobuf:"bytes,14,rep,name=subnets,proto3" json:"subnets,omitempty"`
	Subnet6S             []*Subnet6     `protobuf:"bytes,15,rep,name=subnet6s,proto3" json:"subnet6s,omitempty"`
	Domains              []*Domain      `protobuf:"bytes,16,rep,name=domains,proto3" json:"domains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Content) GetEntryType() int32 {
	if m != nil {
		return m.EntryType
	}
	return 0
}

func (m *Content) GetHttpsBlock() int32 {
	if m != nil {
		return m.HttpsBlock
	}
	return 0
}

func (m *Content) GetRegistryUpdateTime() int64 {
	if m != nil {
		return m.RegistryUpdateTime
	}
	return 0
}

func (m *Content) GetDecision() *Decision {
	if m != nil {
		return m.Decision
	}
	return nil
}

func (m *Content) GetIncludeTime() int64 {
	if m != nil {
		return m.IncludeTime
	}
	return 0
}

func (m *Content) GetBlockType() string {
	if m != nil {
		return m.BlockType
	}
	return ""
}

func (m *Content) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Content) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Content) GetU2Hash() uint32 {
	if m != nil {
		return m.U2Hash
	}
	return 0
}

func (m *Content) GetUrls() []*URL {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *Content) GetIp4S() []*IPv4Address {
	if m != nil {
		return m.Ip4S
	}
	return nil
}

func (m *Content) GetIp6S() []*IPv6Address {
	if m != nil {
		return m.Ip6S
	}
	return nil
}

func (m *Content) GetSubnets() []*Subnet {
	if m != nil {
		return m.Subnets
	}
	return nil
}

func (m *Content) GetSubnet6S() []*Subnet6 {
	if m != nil {
		return m.Subnet6S
	}
	return nil
}

func (m *Content) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

type Decision struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Org                  string   `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Decision) Reset()         { *m = Decision{} }
func (m *Decision) String() string { return proto.CompactTextString(m) }
func (*Decision) ProtoMessage()    {}
func (*Decision) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *Decision) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Decision.Unmarshal(m, b)
}
func (m *Decision) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Decision.Marshal(b, m, deterministic)
}
func (m *Decision) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Decision.Merge(m, src)
}
func (m *Decision) XXX_Size() int {
	return xxx_messageInfo_Decision.Size(m)
}
func (m *Decision) XXX_DiscardUnknown() {
	xxx_messageInfo_Decision.DiscardUnknown(m)
}

var xxx_messageInfo_Decision proto.InternalMessageInfo

func (m *Decision) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Decision) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Decision) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

type IPv4Address struct {
	Ip4                  uint32   `protobuf:"varint,1,opt,name=ip4,proto3" json:"ip4,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPv4Address) Reset()         { *m = IPv4Address{} }
func (m *IPv4Address) String() string { return proto.CompactTextString(m) }
func (*IPv4Address) ProtoMessage()    {}
func (*IPv4Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *IPv4Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPv4Address.Unmarshal(m, b)
}
func (m *IPv4Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPv4Address.Marshal(b, m, deterministic)
}
func (m *IPv4Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPv4Address.Merge(m, src)
}
func (m *IPv4Address) XXX_Size() int {
	return xxx_messageInfo_IPv4Address.Size(m)
}
func (m *IPv4Address) XXX_DiscardUnknown() {
	xxx_messageInfo_IPv4Address.DiscardUnknown(m)
}

var xxx_messageInfo_IPv4Address proto.InternalMessageInfo

func (m *IPv4Address) GetIp4() uint32 {
	if m != nil {
		return m.Ip4
	}
	return 0
}

func (m *IPv4Address) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type IPv6Address struct {
	Ip6                  string   `protobuf:"bytes,1,opt,name=ip6,proto3" json:"ip6,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPv6Address) Reset()         { *m = IPv6Address{} }
func (m *IPv6Address) String() string { return proto.CompactTextString(m) }
func (*IPv6Address) ProtoMessage()    {}
func (*IPv6Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *IPv6Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPv6Address.Unmarshal(m, b)
}
func (m *IPv6Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPv6Address.Marshal(b, m, deterministic)
}
func (m *IPv6Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPv6Address.Merge(m, src)
}
func (m *IPv6Address) XXX_Size() int {
	return xxx_messageInfo_IPv6Address.Size(m)
}
func (m *IPv6Address) XXX_DiscardUnknown() {
	xxx_messageInfo_IPv6Address.DiscardUnknown(m)
}

var xxx_messageInfo_IPv6Address proto.InternalMessageInfo

func (m *IPv6Address) GetIp6() string {
	if m != nil {
		return m.Ip6
	}
	return ""
}

func (m *IPv6Address) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type Subnet struct {
	Subnet               string   `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subnet) Reset()         { *m = Subnet{} }
func (m *Subnet) String() string { return proto.CompactTextString(m) }
func (*Subnet) ProtoMessage()    {}
func (*Subnet) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *Subnet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subnet.Unmarshal(m, b)
}
func (m *Subnet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subnet.Marshal(b, m, deterministic)
}
func (m *Subnet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subnet.Merge(m, src)
}
func (m *Subnet) XXX_Size() int {
	return xxx_messageInfo_Subnet.Size(m)
}
func (m *Subnet) XXX_DiscardUnknown() {
	xxx_messageInfo_Subnet.DiscardUnknown(m)
}

var xxx_messageInfo_Subnet proto.InternalMessageInfo

func (m *Subnet) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

func (m *Subnet) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type Subnet6 struct {
	Subnet6              string   `protobuf:"bytes,1,opt,name=subnet6,proto3" json:"subnet6,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subnet6) Reset()         { *m = Subnet6{} }
func (m *Subnet6) String() string { return proto.CompactTextString(m) }
func (*Subnet6) ProtoMessage()    {}
func (*Subnet6) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *Subnet6) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subnet6.Unmarshal(m, b)
}
func (m *Subnet6) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subnet6.Marshal(b, m, deterministic)
}
func (m *Subnet6) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subnet6.Merge(m, src)
}
func (m *Subnet6) XXX_Size() int {
	return xxx_messageInfo_Subnet6.Size(m)
}
func (m *Subnet6) XXX_DiscardUnknown() {
	xxx_messageInfo_Subnet6.DiscardUnknown(m)
}

var xxx_messageInfo_Subnet6 proto.InternalMessageInfo

func (m *Subnet6) GetSubnet6() string {
	if m != nil {
		return m.Subnet6
	}
	return ""
}

func (m *Subnet6) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type URL struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URL) Reset()         { *m = URL{} }
func (m *URL) String() string { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()    {}
func (*URL) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{8}
}

func (m *URL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URL.Unmarshal(m, b)
}
func (m *URL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URL.Marshal(b, m, deterministic)
}
func (m *URL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URL.Merge(m, src)
}
func (m *URL) XXX_Size() int {
	return xxx_messageInfo_URL.Size(m)
}
func (m *URL) XXX_DiscardUnknown() {
	xxx_messageInfo_URL.DiscardUnknown(m)
}

var xxx_messageInfo_URL proto.InternalMessageInfo

func (m *URL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *URL) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type Domain struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{9}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Domain) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*Content)(nil), "Content")
	proto.RegisterType((*Decision)(nil), "Decision")
	proto.RegisterType((*IPv4Address)(nil), "IPv4Address")
	proto.RegisterType((*IPv6Address)(nil), "IPv6Address")
	proto.RegisterType((*Subnet)(nil), "Subnet")
	proto.RegisterType((*Subnet6)(nil), "Subnet6")
	proto.RegisterType((*URL)(nil), "URL")
	proto.RegisterType((*Domain)(nil), "Domain")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x93, 0xb6, 0x69, 0x6e, 0xd7, 0x6e, 0xb2, 0x10, 0xb2, 0x10, 0x42, 0x21, 0x02, 0x51,
	0x5e, 0x02, 0xea, 0xaa, 0x48, 0xf0, 0x06, 0xec, 0x61, 0xa0, 0x3d, 0x20, 0x77, 0xfd, 0x80, 0xb6,
	0xb1, 0x5a, 0x8b, 0x34, 0xc9, 0x6c, 0x67, 0x52, 0xff, 0x9b, 0x0f, 0x40, 0xbe, 0xb6, 0xd7, 0x96,
	0xee, 0xed, 0x9e, 0x73, 0xcf, 0xbd, 0x39, 0x3e, 0x4e, 0x02, 0xf1, 0x4e, 0x6d, 0xb2, 0x46, 0xd6,
	0xba, 0x4e, 0xbf, 0xc0, 0x68, 0xce, 0x97, 0x72, 0xbd, 0x65, 0xfc, 0xa1, 0xe5, 0x4a, 0x13, 0x02,
	0x5d, 0xbd, 0x6f, 0x38, 0xed, 0x24, 0x9d, 0xc9, 0x88, 0x61, 0x4d, 0x5e, 0x40, 0xef, 0xa1, 0xe5,
	0x72, 0x4f, 0x83, 0xa4, 0x33, 0x89, 0x99, 0x05, 0xe9, 0x2f, 0x18, 0xfb, 0x51, 0xd5, 0xd4, 0x95,
	0x42, 0x1d, 0x97, 0xb2, 0x96, 0x38, 0x1c, 0x33, 0x0b, 0x48, 0x0a, 0x91, 0xe4, 0xaa, 0x2d, 0xb5,
	0xa2, 0x41, 0x12, 0x4e, 0x86, 0xd3, 0x41, 0xf6, 0xa3, 0xae, 0x34, 0xaf, 0x34, 0xf3, 0x8d, 0xf4,
	0x6f, 0x08, 0x91, 0x23, 0xc9, 0x18, 0x02, 0x51, 0xe0, 0x8a, 0x1e, 0x0b, 0x44, 0x41, 0x5e, 0x43,
	0xcc, 0x2b, 0x2d, 0xf7, 0xf7, 0xc6, 0x56, 0x80, 0xf4, 0x81, 0x20, 0x6f, 0x00, 0xb6, 0x5a, 0x37,
	0xea, 0x7b, 0x59, 0xaf, 0xff, 0xd0, 0x10, 0xdb, 0x47, 0x0c, 0xc9, 0x80, 0x48, 0xbe, 0x11, 0x4a,
	0xcb, 0xfd, 0xa2, 0x29, 0x96, 0x9a, 0xdf, 0x8b, 0x1d, 0xa7, 0xdd, 0xa4, 0x33, 0x09, 0xd9, 0x33,
	0x1d, 0xf2, 0x1e, 0x06, 0x05, 0x5f, 0x0b, 0x25, 0xea, 0x8a, 0xf6, 0x92, 0xce, 0x64, 0x38, 0x8d,
	0xb3, 0x1b, 0x47, 0xb0, 0xa7, 0x16, 0x49, 0x60, 0x28, 0xaa, 0x75, 0xd9, 0x16, 0x76, 0x5f, 0x1f,
	0xf7, 0x1d, 0x53, 0xc6, 0xf6, 0xca, 0x38, 0x40, 0xdb, 0x11, 0x06, 0x72, 0x20, 0x4c, 0xcc, 0xdb,
	0xa5, 0xda, 0xd2, 0x01, 0x36, 0xb0, 0x36, 0x07, 0xd7, 0x8a, 0xc6, 0xb8, 0x2a, 0xd0, 0x8a, 0xbc,
	0x84, 0x7e, 0x3b, 0xbd, 0x35, 0x2a, 0xc0, 0xcb, 0x70, 0x88, 0x50, 0xe8, 0xb6, 0xb2, 0x54, 0x74,
	0x88, 0x69, 0x76, 0xb3, 0x05, 0xbb, 0x63, 0xc8, 0x90, 0x04, 0xba, 0xa2, 0x99, 0x29, 0x7a, 0x81,
	0x9d, 0x8b, 0xec, 0xe7, 0xef, 0xc7, 0xd9, 0xb7, 0xa2, 0x90, 0x5c, 0x29, 0x86, 0x1d, 0xab, 0xc8,
	0x15, 0x1d, 0x1d, 0x14, 0xf9, 0x91, 0x22, 0x57, 0xe4, 0x2d, 0x44, 0xaa, 0x5d, 0x55, 0x5c, 0x2b,
	0x3a, 0x46, 0x51, 0x94, 0xcd, 0x11, 0x33, 0xcf, 0x93, 0x77, 0x30, 0xb0, 0x65, 0xae, 0xe8, 0xa5,
	0xbb, 0x52, 0xab, 0xc9, 0xd9, 0x53, 0xc7, 0x2c, 0x2a, 0xea, 0xdd, 0x52, 0x54, 0x8a, 0x5e, 0xb9,
	0x45, 0x37, 0x88, 0x99, 0xe7, 0xd3, 0x5b, 0x18, 0xf8, 0x6c, 0x4d, 0x22, 0xe6, 0x12, 0xdc, 0xbb,
	0x83, 0xb5, 0x49, 0xa0, 0x6a, 0x77, 0x2b, 0x2e, 0xdd, 0x9b, 0xe7, 0x10, 0xb9, 0x82, 0xb0, 0x96,
	0x1b, 0xbc, 0xed, 0x98, 0x99, 0x32, 0xfd, 0x04, 0xc3, 0xa3, 0xc3, 0x1a, 0x81, 0x68, 0x66, 0xee,
	0x25, 0x36, 0xa5, 0x0b, 0x37, 0xf0, 0xe1, 0xba, 0x81, 0xfc, 0x64, 0x20, 0x77, 0x0f, 0x37, 0xe5,
	0xd9, 0xc0, 0x67, 0xe8, 0xdb, 0x33, 0x1a, 0x57, 0xf6, 0x90, 0x4e, 0xee, 0xd0, 0xd9, 0xc4, 0x35,
	0x44, 0x2e, 0x15, 0x42, 0x7d, 0xa8, 0xfe, 0x11, 0x1e, 0x9e, 0x0d, 0x7d, 0x80, 0x70, 0xc1, 0xee,
	0x8c, 0x9f, 0x56, 0x96, 0xde, 0x4f, 0x2b, 0xcb, 0xe7, 0xfc, 0xd8, 0x38, 0x8d, 0x1f, 0x1b, 0xa8,
	0xf7, 0x63, 0xd1, 0xff, 0x13, 0xd3, 0xaf, 0xfe, 0x5b, 0x9f, 0x73, 0xf9, 0x28, 0xd6, 0x9c, 0x7c,
	0x84, 0xbe, 0x25, 0xc8, 0x38, 0x3b, 0xf9, 0x0b, 0xbc, 0xba, 0xcc, 0x4e, 0x3f, 0xed, 0x55, 0x1f,
	0x7f, 0x17, 0xd7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x93, 0x07, 0xca, 0x3b, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
